# Use Maven to build the project
FROM maven:3.9.6-eclipse-temurin-21 AS build

# Set work directory inside container
WORKDIR /app

# Copy pom.xml and download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copy source code
COPY src ./src

# Package the Spring Boot application (skip tests since they use in-memory db)
RUN mvn clean package -DskipTests

# Use lightweight JVM image to run the app
FROM eclipse-temurin:21-jdk-alpine

# Create directory for the app
WORKDIR /app

# Copy the JAR file from the build stage
COPY --from=build /app/target/airline-management-system-0.0.1-SNAPSHOT.jar app.jar

# Expose port Spring Boot will run on
EXPOSE 8082

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
